apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: soham/backend
        imagePullPolicy: Never 
        ports:
        - containerPort: 4904
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/test"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  ports:
  - port: 4904
    targetPort: 4904
    nodePort: 30064
  selector:
    app: backend 