apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorillas-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gorillas-backend
  template:
    metadata:
      labels:
        app: gorillas-backend
    spec:
      containers:
      - name: gorillas-backend
        image: wildwarrior44/gorillas-backend:latest
        ports:
        - containerPort: 4904
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: gorillas-backend-service
spec:
  type: NodePort
  ports:
  - port: 4904
    targetPort: 4904
    nodePort: 30064
  selector:
    app: gorillas-backend 